AWSTemplateFormatVersion: "2010-09-09"
Description: >
  A sample CloudFormation template to deploy an EC2 instance with a security group.
  This template demonstrates the use of Parameters, Mappings, and Resources.

Parameters:
  InstanceType:
    Description: Type of EC2 instance
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
    ConstraintDescription: Must be a valid EC2 instance type.
  
  KeyName:
    Description: Name of an existing EC2 KeyPair for SSH access
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.

  Environment:
    Description: Deployment environment (e.g., Dev, Test, Prod)
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Test
      - Prod
    ConstraintDescription: Must be one of Dev, Test, or Prod.

Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0e472ba40eb589f49 # Amazon Linux 2 AMI ID for us-east-1
    us-west-2:
      AMI: ami-02e136e904f3da870 # Amazon Linux 2 AMI ID for us-west-2

Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref MySecurityGroup
      ImageId: 
        # Dynamically fetch the correct AMI ID based on region
        !FindInMap 
          - RegionMap
          - !Ref "AWS::Region"
          - AMI

Outputs:
  InstanceId:
    Description: ID of the created EC2 instance
    Value: !Ref MyEC2Instance
  InstancePublicIP:
    Description: Public IP address of the EC2 instance
    Value: !GetAtt MyEC2Instance.PublicIp
  SecurityGroupId:
    Description: ID of the created Security Group
    Value: !Ref MySecurityGroup
