Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: XXXXXXXXXXXXXXXXXXXXX  # Replace with a valid AMI ID
      InstanceType: t2.micro  # Replace with the desired instance type
